version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: esbuild
    versions:
    - 0.11.0
    - 0.9.0
  - dependency-name: idb
    versions:
    - 6.0.0
